esphome:
  name: ceilsense-basic-wifi-ld2412
  friendly_name: CeilSense v1 Basic (WiFi + LD2412)

packages:
  base: !include base.yaml
  net: !include wifi.yaml
  ld2412: !include packages/ld2412.yaml
