# Complete Ethernet + LD2412 required (SCD4x required)
esphome:
  name: ceilsense-complete-eth-ld2412
  friendly_name: CeilSense v1 Complete (Ethernet + LD2412)

packages:
  base: !include base.yaml
  net: !include eth.yaml
  ld2412: !include packages/ld2412.yaml
  scd4x: !include packages/scd4x.yaml
