# Complete WiFi (SCD4x required, LD2412 optional)
substitutions:
  device_name: ceilsense
  friendly_name: "CeilSense"
  ceilsense_hardware_version: "v1-complete-wifi"
  wifi_update_manifest_url: "https://smarthomeshop.github.io/ceilsense/ceilsense-complete-wifi-manifest.json"
  eth_update_manifest_url: "https://smarthomeshop.github.io/ceilsense/ceilsense-complete-eth-manifest.json"
  default_network: "WiFi"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  base: !include base.yaml
  net: !include wifi.yaml
  scd4x: !include packages/scd4x.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ceilsense/ceilsense-v1/ceilsense-complete-wifi.yaml@main
  import_full_config: false
