# Basic WiFi (no SCD4x, LD2412 optional)
substitutions:
  require_scd4x: "false"
  require_ld2412: "false"

esphome:
  name: ceilsense-basic-wifi
  friendly_name: CeilSense v1 Basic (WiFi)

packages:
  base: !include base.yaml
  net: !include wifi.yaml
