substitutions:
  device_name: ceilsense
  friendly_name: "CeilSense"
  ceilsense_hardware_version: "v1-basic-eth"
  update_manifest_url: "https://smarthomeshop.github.io/ceilsense/ceilsense-basic-eth-manifest.json"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  base: !include base.yaml
  net: !include eth.yaml
