# Complete WiFi (SCD4x required, LD2412 optional)
substitutions:
  device_name: ceilsense
  friendly_name: "CeilSense"
  ceilsense_hardware_version: "v1-complete-wifi"
  update_manifest_url: "https://smarthomeshop.github.io/ceilsense/ceilsense-complete-wifi-manifest.json"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  base: !include base.yaml
  net: !include wifi.yaml
  scd4x: !include packages/scd4x.yaml
