# Basic Ethernet (no SCD4x, LD2412 optional)
substitutions:
  require_scd4x: "false"
  require_ld2412: "false"

esphome:
  name: ceilsense-basic-eth
  friendly_name: CeilSense v1 Basic (Ethernet)

packages:
  base: !include base.yaml
  net: !include eth.yaml
