# Complete Ethernet + LD2412 required (SCD4x required)
substitutions:
  device_name: ceilsense
  friendly_name: "CeilSense"
  ceilsense_hardware_version: "v1-complete-eth-ld2412"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  base: !include base.yaml
  net: !include eth.yaml
  ld2412: !include packages/ld2412.yaml
  scd4x: !include packages/scd4x.yaml
