# Complete WiFi + LD2412 required (SCD4x required)
substitutions:
  device_name: ceilsense
  friendly_name: "CeilSense"
  ceilsense_hardware_version: "v1-complete-wifi-ld2412"
  update_manifest_url: "https://smarthomeshop.github.io/ceilsense/ceilsense-complete-wifi-ld2412-manifest.json"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  base: !include base.yaml
  net: !include wifi.yaml
  ld2412: !include packages/ld2412.yaml
  scd4x: !include packages/scd4x.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ceilsense/ceilsense-v1/ceilsense-complete-wifi-ld2412.yaml@main
  import_full_config: false
