# yamllint disable
# CeilSense v1 - Debug versie om crash te lokaliseren

substitutions:
  device_name: ceilsense-debug
  friendly_name: "CeilSense Debug"
  project_name: "smarthomeshop.ceilsense"
  project_version: "1.3-debug"
  wifi_ssid: "REPLACE_WITH_YOUR_SSID"
  wifi_password: "REPLACE_WITH_YOUR_PASSWORD"
  log_level: "DEBUG"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: ${log_level}
  baud_rate: 115200
  hardware_uart: UART0

api:

ota:
  - platform: esphome

wifi:
  ap:
    password: "ceilsense"

captive_portal:

web_server:
  port: 80

# Globals (minimaal)
globals:
  - id: startup_phase
    type: int
    restore_value: no
    initial_value: '0'

# Alleen I2C zonder sensoren om te testen
i2c:
  sda: GPIO11
  scl: GPIO10
  scan: true
  id: bus_a
  frequency: 100kHz  # Lagere frequentie voor stabiliteit

# Status LED
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO20
    num_leds: 16
    chipset: ws2812
    id: status_led
    name: "Status LED"
    restore_mode: ALWAYS_OFF

# Minimale sensoren - voeg er één voor één bij toe
sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
    
# Stap 1: Alleen BH1750 testen
  - platform: bh1750
    name: "BH1750 Illuminance"
    id: illuminance
    address: 0x23
    update_interval: 60s

switch:
  - platform: template
    name: "Debug Mode"
    id: debug_mode
    optimistic: true

button:
  - platform: restart
    name: "Restart"
