# Ethernet (W5500) mixin for variants
ethernet:
  type: W5500
  clk_pin: GPIO21
  mosi_pin: GPIO45
  miso_pin: GPIO38
  cs_pin: GPIO41
  interrupt_pin: GPIO39
  reset_pin: GPIO40

esphome:
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            id(startup_phase) = 1;
        - light.turn_on:
            id: status_led
            brightness: 80%
            effect: "Circulair Laad Effect"
        # For Ethernet, wait for API connection instead of WiFi
        - wait_until:
            condition:
              api.connected:
            timeout: 30s
        - if:
            condition:
              not:
                api.connected:
            then:
              - lambda: |-
                  id(startup_failed) = true;
        # Final LED indication happens in base after sensor phases
