sensor:
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
      id: scd41_co2
    temperature:
      name: "SCD41 Temperature"
      id: scd41_temperature
      filters:
        - lambda: |-
            return x + id(scd4x_temp_offset).state;
    humidity:
      name: "SCD41 Humidity"
      id: scd41_humidity
      filters:
        - lambda: |-
            return x + id(scd4x_humidity_offset).state;
    measurement_mode: low_power_periodic
    update_interval: 30s
    automatic_self_calibration: false
    temperature_offset: 10.0  # Vaste offset voor ESP warmte compensatie
    ambient_pressure_compensation_source: bmp_pressure

number:
  - platform: template
    name: "SCD4x Extra Temperature Offset (°C)"
    id: scd4x_temp_offset
    icon: mdi:thermometer-plus
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 7.9  # Extra offset bovenop vaste 10°C
    min_value: -20.0
    max_value: 20.0
    step: 0.1
    unit_of_measurement: "°C"
    mode: box
    on_value:
      then:
        - lambda: |-
            id(scd4x_temp_offset_f).publish_state(x * 9.0 / 5.0);

  - platform: template
    name: "SCD4x Extra Temperature Offset (°F)"
    id: scd4x_temp_offset_f
    icon: mdi:thermometer-plus
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 14.22  # 7.9°C in Fahrenheit
    min_value: -36.0  # -20°C in Fahrenheit
    max_value: 36.0   # 20°C in Fahrenheit  
    step: 0.1
    unit_of_measurement: "°F"
    mode: box
    on_value:
      then:
        - number.set:
            id: scd4x_temp_offset
            value: !lambda |-
              return (x * 5.0 / 9.0);

  - platform: template
    name: "SCD4x Humidity Offset (%)"
    id: scd4x_humidity_offset
    icon: mdi:water-percent
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0.0
    min_value: -20.0
    max_value: 20.0
    step: 0.1
    unit_of_measurement: "%"
    mode: box

esphome:
  # Zelftest fase 3: SCD4x waarden
  on_boot:
    - priority: 560
      then:
        - lambda: 'id(scd4x_required) = true;'
        - lambda: |-
            id(startup_phase) = 3;
        # Sync Fahrenheit offset with Celsius offset
        - lambda: |-
            id(scd4x_temp_offset_f).publish_state(id(scd4x_temp_offset).state * 9.0 / 5.0);
        - wait_until:
            condition:
              lambda: |-
                return id(scd41_co2).has_state() && id(scd41_temperature).has_state() && id(scd41_humidity).has_state() &&
                       !isnan(id(scd41_co2).state) && !isnan(id(scd41_temperature).state) && !isnan(id(scd41_humidity).state);
            timeout: 45s
        - if:
            condition:
              lambda: |-
                return !id(scd41_co2).has_state() || !id(scd41_temperature).has_state() || !id(scd41_humidity).has_state() ||
                       isnan(id(scd41_co2).state) || isnan(id(scd41_temperature).state) || isnan(id(scd41_humidity).state);
            then:
              - lambda: |-
                  id(startup_failed) = true;
        - lambda: 'id(scd4x_checked) = true;'