sensor:
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
      id: scd41_co2
    temperature:
      name: "SCD41 Temperature"
      id: scd41_temperature
    humidity:
      name: "SCD41 Humidity"
      id: scd41_humidity
      filters:
        offset: 4
    measurement_mode: low_power_periodic
    update_interval: 30s
    automatic_self_calibration: false
    temperature_offset: 17.9
    ambient_pressure_compensation_source: bmp_pressure


esphome:
  # Zelftest fase 3: SCD4x waarden
  on_boot:
    - priority: 560
      then:
        - lambda: |-
            id(startup_phase) = 3;
        - wait_until:
            condition:
              lambda: |-
                return !isnan(id(scd41_co2).state) && !isnan(id(scd41_temperature).state) && !isnan(id(scd41_humidity).state);
            timeout: 45s
        - if:
            condition:
              lambda: |-
                return isnan(id(scd41_co2).state) || isnan(id(scd41_temperature).state) || isnan(id(scd41_humidity).state);
            then:
              - lambda: |-
                  id(startup_failed) = true;