name: Build and Publish CeilSense firmware and website

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-ceilsense-basic-wifi:
    name: Publish CeilSense Basic WiFi
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-basic-wifi.yaml
      name: CeilSense Basic WiFi
      manifest_filename: ceilsense-basic-wifi-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-basic-wifi
  publish-ceilsense-basic-wifi-ld2412:
    name: Publish CeilSense Basic WiFi LD2412
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-basic-wifi-ld2412.yaml
      name: CeilSense Basic WiFi LD2412
      manifest_filename: ceilsense-basic-wifi-ld2412-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-basic-wifi-ld2412
  publish-ceilsense-basic-eth:
    name: Publish CeilSense Basic Ethernet
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-basic-eth.yaml
      name: CeilSense Basic Ethernet
      manifest_filename: ceilsense-basic-eth-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-basic-eth
  publish-ceilsense-basic-eth-ld2412:
    name: Publish CeilSense Basic Ethernet LD2412
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-basic-eth-ld2412.yaml
      name: CeilSense Basic Ethernet LD2412
      manifest_filename: ceilsense-basic-eth-ld2412-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-basic-eth-ld2412
  publish-ceilsense-complete-wifi:
    name: Publish CeilSense Complete WiFi
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-complete-wifi.yaml
      name: CeilSense Complete WiFi
      manifest_filename: ceilsense-complete-wifi-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-complete-wifi
  publish-ceilsense-complete-wifi-ld2412:
    name: Publish CeilSense Complete WiFi LD2412
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-complete-wifi-ld2412.yaml
      name: CeilSense Complete WiFi LD2412
      manifest_filename: ceilsense-complete-wifi-ld2412-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-complete-wifi-ld2412
  publish-ceilsense-complete-eth:
    name: Publish CeilSense Complete Ethernet
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-complete-eth.yaml
      name: CeilSense Complete Ethernet
      manifest_filename: ceilsense-complete-eth-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-complete-eth
  publish-ceilsense-complete-eth-ld2412:
    name: Publish CeilSense Complete Ethernet LD2412
    uses: ./.github/workflows/esphome-build.yml
    with:
      files: ceilsense-v1/ceilsense-complete-eth-ld2412.yaml
      name: CeilSense Complete Ethernet LD2412
      manifest_filename: ceilsense-complete-eth-ld2412-manifest.json
      clean: false
      esphome_version: latest
      directory_name: ceilsense-complete-eth-ld2412
